Changefile "%1" "-{" ""
Changefile "%1" "|{" ""
Changefile "%1" "*{" ""
Changefile "%1" "_{" "_"
Changefile "%1" "^{" "_"
Changefile "%1" "}-" ""
Changefile "%1" "}*" ""
Changefile "%1" "}|" ""
Changefile "%1" "}_" ""
Changefile "%1" "}^" "_"
Changefile "%1" "<-" "="
Changefile "%1" "(*)" "*"
Changefile "%1" "_le_" "<="
Changefile "%1" "_ge_" ">="
Changefile "%1" "_eq_" "=="
Changefile "%1" "_ne_" "!="
Changefile "%1" "_lt_" "<"
Changefile "%1" "_gt_" ">"
Changefile "%1" "_or_" "||"
Changefile "%1" "_and_" "&&"
Changefile "%1" "_not_" "!"
Changefile "%1" "_xor_" "^"
Changefile "%1" "mod" "%%"
Changefile "%1" "then" "{"
Changefile "%1" "begin" "{"
Changefile "%1" "start" "{"
Changefile "%1" "stop" "}"
Changefile "%1" "end loop" "}"
Changefile "%1" "end if" "}"
Changefile "%1" "end for" "}"
Changefile "%1" "[[" "&lang;"
Changefile "%1" "]]" "&rang;"